server:
  port: 8081

spring:
  application:
    name: usuarios-service
  datasource:
    url: jdbc:postgresql://localhost:5433/usuarios_db
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /docs